### ISSUE TITLE
Documentation Suggestion

### ISSUE THREAD

**Issue by thelaughingwolf** [ElementaryFramework/WaterPipe#4]
The problem I had in following along with the tutorials was that the WaterPipe file was never being called. If I hit the root, it worked, but otherwise I got my hosting provider's 404 page instead.

After Googling, I realized the tutorials must expect any user to set up their own `.htaccess` file with a RewriteRule to make sure the WaterPipe actually gets called. Once I did that, WaterPipe worked like a dream. But I think that step should be in the Wiki somewhere.

**Comment by na2axl** [comment]
Hi @thelaughingwolf, and thank you for using WaterPipe. I agree with you, this must be added in documentations.
I will write a **Deploy step** in the Getting Started page of the wiki and in the tutorial on dev.to, showing how to configure Apache HTTP and NGiNX to work with WaterPipe based projects.

**Comment by na2axl** [comment]
Hi @thelaughingwolf , the [Deploy step](https://github.com/ElementaryFramework/WaterPipe/wiki/Getting-Started#deploy-it) has been added in the wiki and the post on dev.to. 
Sorry for the late.
